spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user-service-db}
spring.datasource.username=${DB_USERNAME:user_admin}
spring.datasource.password=${DB_PASSWORD:33563356}

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}